name: Deploy Miranda to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to EC2 Server
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
        run: |
          # Conexi贸n y actualizaci贸n del c贸digo en el servidor EC2
          ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST << 'EOF'
          
            # Cambiar a la carpeta del proyecto en el servidor
            cd /var/www/miranda_laravel/hotelmirandalaravel || exit 1

            # Configurar el directorio como seguro en Git
            git config --global --add safe.directory /var/www/miranda_laravel/hotelmirandalaravel

            # Actualizar el repositorio
            git pull origin main || exit 1

            # Instalar dependencias de Laravel (PHP)
            if [ -f "composer.json" ]; then
              composer install --no-interaction --prefer-dist --optimize-autoloader || exit 1
            fi

             # Instalar dependencias de Node.js (npm)
            if [ -f "package.json" ]; then
              npm install || exit 1
            fi

            # Ejecutar la compilaci贸n de los assets con npm
            npm run build || exit 1

            # Migraciones para Laravel (PHP)
            if [ -f "artisan" ]; then
              php artisan migrate --force || exit 1
            fi

            # Limpiar vistas y cache de Laravel
            php artisan config:cache || exit 1
            php artisan route:cache || exit 1
            php artisan view:clear || exit 1

            # Reiniciar Apache2 para aplicar los cambios
            sudo systemctl restart apache2 || exit 1

          EOF
